### PR TITLE
Update polish translation

### PR DESCRIPTION
**Pull request by izikeros**
Update to several strings after seeing them in the game - more accurate translation when saw text in the context or adjust size to the width of display window. Additionally, translation template (rttr.pot) was updated and polish translation file was adjusted to that template (not fully sure if this approach is correct from translations maintenance point of view).

### CODE REVIEW

**Comment by Flow86** [comment]
Hi,

as long as you have run `make -B translations` to sort the files (but I think you did?) the process should be fine!

**Comment by Flamefire** [comment]
> run make -B translations to sort the files (but I think you did?)

The translation file looks unsorted. E.g. "winterworld" moved from bottom to top.

@Flow86 Can you do that? Should we just add some simple CI here?

**Comment by izikeros** [comment]
I have updated template with poedit not using `make -B translations`, then aligned polish translation to refreshed template. When running `make -B translations` I have all *.po and *.pot file updated. I'm already learning how gettext-based localization works. I need some time to clean this up. I will update my local master to recent version run `make -B translations`, commit, provide polish translation updates and commit.

**Comment by Flamefire** [comment]
@izikeros For this you can simply run `msgmerge --sort-output --no-wrap --quiet --update --backup=none rttr-pl.po rttr.pot`, then commit the change again.

**Comment by Flamefire** [comment]
Thanks for the update, the translation file looks good now.
But I think something went wrong here. Your second pot commit https://github.com/Return-To-The-Roots/languages/pull/17/commits/8de63bd41e00d281f9abd477ec63fd74c3b644b3 undid the changes from https://github.com/Return-To-The-Roots/languages/pull/17/commits/55d0e3ffdf34e4d5e778b81982e6d6615254f7aa, so a few of the new translations are now missing. Was this on purpose? Or did you maybe run the pot update on an older RTTR checkout?

I can merge this as-is or you can include the pot update and new translations if you want.

**Pull request merged**
