### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by Flamefire**
Fixes the following (in order of commits):
- Run a `make -B translations` so all translations are consistently sorted (good for imports/updates)
- Import new translations from launchpad (and sort them so diff stays small)
- Fix metadata so editing with poedit is easier (also fix source encoding to UTF-8)
- Update POT file (refactoring introduced many changes)
- Update the PO files from the POT file
- Complete the German translation

Note: Includes the string from the new Addon-branch

@Flow86 Can you double-check if all is correct and merge?

### CODE REVIEW

**Comment by Flamefire** [comment]
@Flow86 Can you check why LP does not import them? https://translations.launchpad.net/s25rttr/s25client/+imports shows "No import target selected" Or does it just take some more time?
I've also seen, that when downloading, the existing files (in git) are in one directory and the new files (translations not existent on git) are in another directory. Maybe this is the problem there?

**Comment by Flamefire** [comment]
And the build server has problems with this as the po files where modified (resorting... should not happen after that PR anymore as they are already sorted)
Could you delete the workspace and/or make jenkins issue a git reset before a checkout?

**Comment by Flow86** [comment]
yea launchpad does not import them since their language is not set (anymore) since the subversion to git import

**Comment by Flow86** [comment]
no they're not sorted, since every gettext version sorts differently :-/

**Comment by Flamefire** [comment]
Is it possible to set them again? Or do you need to approve everything manually every time we push an update?

I see. The messages get sorted the same as it seems but the meta data not... Why does the windows gettext try to move the `Language` field? :confused:  Well at least the messages are ok...

**Comment by Flamefire** [comment]
@Flow86 I've just seen, that launchpad likes the file names to be their language code name, but we have the `rttr-` prefix. I assume the import would work automatically if the names were changed. (https://help.launchpad.net/Translations/YourProject/ImportPolicy?action=show&redirect=Translations%2FImportPolicy)

Is this right? Or is there another way for automatic approval? Why not rename them? They are in the rttr project/folder anyway

**Comment by Flow86** [comment]
you only have to set the language once per file, then the import works

**Pull request merged**
